source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

def shared_pods
    pod 'SKPhotoBrowser-Kingfisher', :path => '../'
end

target 'SKPhotoBrowser-Kingfisher' do
    shared_pods
end

target 'SKPhotoBrowser-KingfisherTests' do
    shared_pods
end
