source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

def shared_pods
    pod 'SKPhotoBrowser-Kingfisher', :path => '../'
end

target 'SKPhotoBrowser-Kingfisher' do
    shared_pods
end

target 'SKPhotoBrowser-KingfisherTests' do
    shared_pods
end

# Build configurations
post_install do |installer|
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.1'
        end
  end
end
